export const HOME_SCREEN = 'lxm.HomeScreen'
export const PLAY_DETAIL_SCREEN = 'lxm.PlayDetailScreen'
export const SONGLIST_DETAIL_SCREEN = 'lxm.SonglistDetailScreen'
export const COMMENT_SCREEN = 'lxm.CommentScreen'
export const WY_SONGLIST_RECOMMEND_SCREEN = 'lxm.WySonglistRecommendScreen'
export const WY_PLAY_RADIO_SCREEN = 'lxm.WyPlayRadioScreen'
export const VERSION_MODAL = 'lxm.VersionModal'
export const PACT_MODAL = 'lxm.PactModal'
export const SYNC_MODE_MODAL = 'lxm.SyncModeModal'
export const DOWNLOAD_MODAL = 'lxm.DownloadModal'
export const DOWNLOAD_MANAGER_MODAL = 'lxm.DownloadManagerModal'
export const MOD_NOTICE_MODAL = 'lxm.ModNoticeModal'
export const WY_USER_PLAYLIST_MODAL = 'lxm.WyUserPlaylistModal'
export const WY_LOGIN_MODAL = 'lxm.WyLoginModal'
export const WY_QR_LOGIN_MODAL = 'lxm.WyQrLoginModal'
// export const SETTING_SCREEN = 'lxm.SettingScreen'
// export const TOAST_SCREEN = 'lxm.ToastScreen'

